# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15f95dd952d121e26017d72145b76ccc1d991a441ea8ca4b744a23ac3b647c0706c432dad46c51e61e678fe84efe7cc9a98547446c6b302121759d87995481e

test:
  secret_key_base: bf767cf684f00c2f9c9177644dc30f073f095b9e8a973f15674c1cc025524b25cef6a4b4b2be25d61860d2833db341ddae641adbfd8432562ace16c515f7c6ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
